stack=[]
stack.append(0)
stack.append(1)
stack.append(5)
stack.append(2)
stack.append(4)
stack.append(7)
print(stack)
max1 = max(stack)
print(max1)
stack.remove(0)
stack.remove(1)
print(stack)
stack.insert(0,-1)
stack.insert(0,10)
print(stack)
max2 = max(stack)
print(max2)