stack = []
stack.append(5)
stack.append(2)
stack.append(4)
stack.append(7)
print(stack)
max1 = max(stack)
stack.remove(max1)
print(stack)
stack.insert(0,-1)
stack.insert(0,20)
print(stack)
max2 = max(stack)
stack.remove(max2)
print(stack)