stack=[]
stack.append(5)
stack.append(2)
stack.append(4)
stack.append(7)
print(stack)
len1 = len(stack)
middle1 = (stack[len1//2])
print(middle1)
print(stack)
stack.insert(0,-1)
stack.insert(0,-2)
stack.insert(0,-3)
len2=len(stack)
print(stack)
middle2 = (stack[len2//2])
print(middle2)