stack = []
stack.append(5)
stack.append(2)
stack.append(4)
stack.append(7)
print(stack)
min1 = min(stack)
stack.remove(min1)
print(stack)
stack.insert(0,-1)
stack.insert(0,2)
print(stack)
min2 = min(stack)
stack.remove(min2)
print(stack)